# @format

root: true
parserOptions:
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "unicorn"
  - "import"
extends:
  - "airbnb-typescript/base"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:unicorn/recommended"
  - "prettier"
rules:
  unicorn/numeric-separators-style: "off"
  unicorn/filename-case:
    - "error"
    - "case": "pascalCase"
  unicorn/prefer-module: "off"
  unicorn/no-null: "off"
  unicorn/no-useless-undefined: "off"
  unicorn/prefer-spread: "off"
