root: true
parserOptions:
  project: "tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "unicorn"
  - "import"
extends:
  - "airbnb-typescript/base"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:unicorn/recommended"
  # - "plugin:prettier/recommended"
  - "prettier"
  # - "prettier/@typescript-eslint"
